// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Lens = require("./lens.bs.js");
var Karet = require("./karet.bs.js");
var React = require("react");
var KaretUtil = require("karet.util");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var PartialLenses = require("partial.lenses");

var component = ReasonReact.statelessComponent("AddItemForm");

var name = PartialLenses.lens((function (i) {
        return i[/* name */0];
      }), (function (name, i) {
        return /* record */[
                /* name */name,
                /* price */i[/* price */1],
                /* recipe */i[/* recipe */2]
              ];
      }));

var price = PartialLenses.lens((function (i) {
        return i[/* price */1];
      }), (function (price, i) {
        return /* record */[
                /* name */i[/* name */0],
                /* price */price,
                /* recipe */i[/* recipe */2]
              ];
      }));

var recipe = PartialLenses.lens((function (i) {
        return i[/* recipe */2];
      }), (function (recipe, i) {
        return /* record */[
                /* name */i[/* name */0],
                /* price */i[/* price */1],
                /* recipe */recipe
              ];
      }));

var Lens$1 = /* module */[
  /* name */name,
  /* price */price,
  /* recipe */recipe
];

var Item = /* module */[/* Lens */Lens$1];

function make(value, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Karet.Input[/* make */1](KaretUtil.view(name, value), /* array */[])), ReasonReact.element(undefined, undefined, Karet.Input[/* make */1](KaretUtil.view(Lens.Infix[/* <-> */0](price, Lens.string_of_int), value), /* array */[])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var U = 0;

var L = 0;

exports.U = U;
exports.L = L;
exports.component = component;
exports.Item = Item;
exports.make = make;
/* component Not a pure module */
