// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var GraphqlJs = require("graphql.js");

function graphql($staropt$star, $staropt$star$1, $staropt$star$2, url) {
  var headers = $staropt$star !== undefined ? $staropt$star : /* [] */0;
  var method_ = $staropt$star$1 !== undefined ? $staropt$star$1 : "POST";
  var asJSON = $staropt$star$2 !== undefined ? $staropt$star$2 : false;
  var _headers = Js_dict.fromList(headers);
  return GraphqlJs(url, {
              method: method_,
              headers: _headers,
              asJSON: asJSON
            });
}

exports.graphql = graphql;
/* Js_dict Not a pure module */
