// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var PartialLenses = require("partial.lenses");

((/[^0-9]/g));

function string_of_int(param) {
  return PartialLenses.iso((function (prim) {
                return String(prim);
              }), param);
}

function $less$neg$great(prim, prim$1) {
  return PartialLenses.compose(prim, prim$1);
}

var Infix = /* module */[/* <-> */$less$neg$great];

exports.string_of_int = string_of_int;
exports.Infix = Infix;
/*  Not a pure module */
