// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Karet = require("./karet.bs.js");
var Kefir = require("./kefir.bs.js");
var Kefir$1 = require("kefir");
var React = require("react");
var Graphql = require("./graphql.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var KaretUtil = require("karet.util");
var AddItemForm = require("./addItemForm.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function $great$pipe$eq(p, fn) {
  return p.then((function (value) {
                return Promise.resolve(Curry._1(fn, value));
              }));
}

function $great$great$eq(p, fn) {
  return p.then(Curry.__1(fn));
}

var graph = Graphql.graphql(undefined, "POST", true, "http://localhost:3000/graphql");

function run(variables) {
  return $great$pipe$eq(graph.query("\n\tquery {\n\t\titems {\n\t\t\tname\n\t\t\tprice\n\t\t}\n\t}\n\t", variables), (function (data) {
                return $$Array.map((function (item) {
                              return /* record */[
                                      /* name */item.name,
                                      /* price */item.price
                                    ];
                            }), data.items);
              }));
}

var Items = /* module */[/* run */run];

var items = Kefir$1.fromPromise(run(/* () */0)).toProperty((function () {
        return /* array */[];
      }));

var itemsDom = Karet.toDom(Kefir.map((function (s) {
            var l = $$Array.map((function (item) {
                    return React.createElement("li", undefined, item[/* name */0]);
                  }), s);
            return React.createElement("ul", undefined, l);
          }), items));

var initialItem_002 = /* recipe : array */[];

var initialItem = /* record */[
  /* name */"",
  /* price */0,
  initialItem_002
];

var item = KaretUtil.atom(initialItem);

ReactDOMRe.renderToElementWithId(React.createElement("div", undefined, itemsDom, ReasonReact.element(undefined, undefined, AddItemForm.make(item, /* array */[]))), "react");

var U = 0;

var L = 0;

exports.U = U;
exports.L = L;
exports.$great$pipe$eq = $great$pipe$eq;
exports.$great$great$eq = $great$great$eq;
exports.graph = graph;
exports.Items = Items;
exports.items = items;
exports.itemsDom = itemsDom;
exports.initialItem = initialItem;
exports.item = item;
/* graph Not a pure module */
